name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 # Phiên bản mới hơn

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4 # Dùng action chính thức của Docker
        with:
          context: .
          file: docker/Dockerfile # Đường dẫn đến Dockerfile
          push: true
          tags: noskaiser231000/soict:latest # Tên image và tag